### PR TITLE
Introduction of FHIR order-catalog IG

### PR DESCRIPTION
**Pull request by fmacary**
Added the order-catalog line into the SPECS-FHIR.xml file and created the new file FHIR-order-catalog.xml, both in xml folder

### CODE REVIEW

**Comment by fmacary** [comment]
The button was green, so I clicked on it. I guess I'm done with adding order-catalog IG

**Comment by fmacary** [comment]
It seems that my commits have been merged. However I don't see them in the master. Not sure whether I have to take more actions or not.

**Comment by lmckenzi** [comment]
It takes up to 10 minutes to show up once merged.  Confirmed it's there now

**Comment by fmacary** [comment]
Thank you Lloyd. I saw the update.

De : Lloyd McKenzie <notifications@github.com>
Envoyé : mardi 28 juillet 2020 19:26
À : HL7/JIRA-Spec-Artifacts <JIRA-Spec-Artifacts@noreply.github.com>
Cc : François MACARY <francois.macary@phast.fr>; State change <state_change@noreply.github.com>
Objet : Re: [HL7/JIRA-Spec-Artifacts] Introduction of FHIR order-catalog IG (#50)


It takes up to 10 minutes to show up once merged. Confirmed it's there now

**Pull request merged**
