### PR TITLE
Update FHIR-us-sirb.xml

### PR DESCRIPTION
**Pull request by jdtopping**
Enclosed new page item in round brackets

### CODE REVIEW

**Comment by lmckenzi** [comment]
Putting brackets around the qr 'page' won't help.  There are already artifacts for each qr.  You shouldn't have a 'theoretical' page for qrs when you have artifacts for them too.  (In general, you only want one way to provide feedback for a given page in the IG.)

**Comment by jdtopping** [comment]
I didn’t make artifacts for the responses, just the questionnaires.  I was trying to group the feedback for the responses together since there’s likely to be less on the responses themselves.  So they should all be their own artifacts independently?

**Comment by lmckenzi** [comment]
If they're not artifacts listed in the IG, they won't show up at all.  And
I absolutely see them as artifacts in the IG...

*Lloyd McKenzie*, P.Eng. (he/him)
Senior Consultant, Information Technology Services
Gevity Consulting Inc.

 E: ***@***.***
M: +1 587-334-1110 <1-587-334-1110>
W: gevityinc.com

*GEVITY *

*Enabling a healthier world *

CONFIDENTIALITY – This communication is confidential and for the exclusive
use of its intended recipients. If you have received this communication
through error, please notify the sender and delete the message without
copying or disclosing*.*

REPRESENTATION –  Unless explicitly stated otherwise, the opinions and
positions expressed in this e-mail do not necessarily reflect those of my
employer, my clients, nor the organizations with whom I hold governance
positions

**Comment by jdtopping** [comment]
Lloyd-

It looks like I am still getting the warning about the Jira artifact or version tags not matching.  I deprecated the random page and added all the Questionnaireresponses as artifacts.  Any thoughts?  Thanks for your help as always.

James

**Comment by lmckenzi** [comment]
Issue is that the keys had been changed when the ids were corrected.  The keys needed to be left as they were.  (The fact they have spelling/capitalization issues doesn't matter.)  Fixed with a separate commit.

**Comment by jdtopping** [comment]
It looks like I was missing a number of other rows as well, so thanks for the help.

James

**Pull request merged**
