### PR TITLE
Update for STU1.1

### PR DESCRIPTION
**Pull request by minigrrl**

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
It looks like a bunch of things have had their ids changed.  This is being interpreted as an add/remove situation.  However, what you should do is simply use the old key with the new id/names.

**Comment by minigrrl** [comment]
> It looks like a bunch of things have had their ids changed. This is being interpreted as an add/remove situation. However, what you should do is simply use the old key with the new id/names.

@lmckenzi does it really matter? This would be a very large time consuming manual job for me to do (unless there is a way to do it that isn't manual??). Like this is just for the jira drop downs, does it really matter if some artifacts have been deprecated when they have been given new ids and new names?

**Comment by lmckenzi** [comment]
It's how we maintain traceability of what change requests have happened to what artifact over time.  It's also used to help verify maturity.  I recognize it's a bit of a pain, but it is something we've expected of other projects.

**Comment by minigrrl** [comment]
Ok

**Comment by minigrrl** [comment]
@lmckenzi so I think there is a problem here. For BFDR (haven't looked at VRCPL yet), most of the deprecated artifacts were deprecated at the previous publication - and the traceability issue wasn't picked up at that point.  

There were 39 deprecated artifacts in 2021 and there are 54 now. There is clearly nothing we can do about the 39 deprecations that have already been published (in fact, if I try to do the thing with the old key/new id, the build crashes).

14 out of those 15 new deprecations are the profiles and examples we deleted. I've fixed the other one.

**Comment by minigrrl** [comment]
BTW, still working on VRCPL

**Comment by minigrrl** [comment]
Ok @lmckenzi VRCPL did have a bunch where we gave them new ids, so I've fixed those up.

**Review by lmckenzi — APPROVED** [review]

**Pull request merged**
