### PR TITLE
Creating JIRA Spec for mhealth-framework project

### PR DESCRIPTION
**Pull request by keithboone**
Creating JIRA Spec for mhealth-framework project.  Somehow we managed to get this balloted without an initial one.

### CODE REVIEW

**Comment by keithboone** [comment]
Ready for merge

**Review by lmckenzi — CHANGES_REQUESTED** [review]
The URLs for your 'current' and 0.0.1 version aren't correct.

**Comment by lmckenzi** [comment]
<version code="0.0.1" url="http://example.org/fhir/STU1"/>
Typically the first version is 0.1.0, and URL should be the URL we expect the ballot to be hosted at.
Why is .gitignore being added to .gitignore?
Why is saner being modified in this proposal?

**Comment by DavidPyke** [comment]
SANER was added because I'm an idiot and Keith and I use the same repository for the JIRA-spec stuff.  I'll chat with Keith about the mHealth stuff.

**Comment by keithboone** [comment]
I've updated the mhealth Jira spec and fixed the URLs

**Review by lmckenzi — COMMENTED** [review]
I'm still seeing the saner stuff as being completely revamped (because of whitespace changes, hard to see if any changes are actually significant).  Can you roll back the saner change to keep this pull request clean?

**Comment by DavidPyke** [comment]
Yep, I'll clean it out

**Comment by DavidPyke** [comment]
Okay, it's only the mHealth-framework changes now.

**Review by lmckenzi — APPROVED** [review]

**Pull request merged**
