### PR TITLE
Update FHIR-pocd.xml

### PR DESCRIPTION
**Pull request by stefan-karl**
Update FHIR-pocd.xml with unmodified file as generated by the IG publisher (after name changes to distinguish CodeSystem and ValueSet).

### CODE REVIEW

**Comment by stefan-karl** [comment]
The IG publisher removed one line that I added manually because otherwise .buildlocal.bat failed:
<artifact name="Observation" key="Observation" deprecated="true"/>
Is it really needed?

**Comment by lmckenzi** [comment]
Was there an Observation key in the original version?  If so, the publisher shouldn't remove an update that deprecates it...

**Comment by stefan-karl** [comment]
There is an Observation profile with key="StructureDefinition-Observation" in FHIR-pocd.xml.
The entry with key="Observation" was deprecated from beginning.

**Comment by lmckenzi** [comment]
This is extremely stale, so closing

**Pull request closed without merging**
