### PR TITLE
updated FHIR-us-davinci-pdex.xml to latest version

### PR DESCRIPTION
**Pull request by ekivemark**

### CODE REVIEW

**Comment by lmckenzi** [comment]
According to this, nothing changed?

**Comment by ekivemark** [comment]
I exported the jiraspec.xml file from a local build.

Is there something else I should be doing?


—
Mark

**Comment by lmckenzi** [comment]
Has anything actually changed?  Are you getting a message saying that Jira is out of sync?

**Comment by lmckenzi** [comment]
Looks like it's superseded by a new pull request

**Pull request closed without merging**
