### PR TITLE
Trying to update the MDI Jira Spec file for 1.1

### PR DESCRIPTION
**Pull request by DianaWright61**
Trying to update the MDI Jira Spec file for 1.1

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
The version URLs are still not correct.  Make sure they're correct in the registered package-list.json and in your publication-request.json

**Comment by DianaWright61** [comment]
The version 1.1.0 has not been published; it is going through an STU Update comment period now. That is why the url for 1.1.0 is the ciUrl. Is that the correct approach?   I would like the version 1.1.0 to show in the Jira list so commenters can designate specific resources.

**Comment by lmckenzi** [comment]
You shouldn't define 1.1.0 until such time as you're ready to publish 1.1.0.  You also can't do an STU comment period without doing a frozen snapshot release and formal publication request for it...  When you define a URL for 1.1.0, it will have to be STU1.1.

**Review by lmckenzi — CHANGES_REQUESTED** [review]
The URLs for the versions don't make sense.  1.0.0 should still be /mdi/STU1.  The 1.1.0 URL looks wrong.

Also, why is the table of contents deprecated?

**Pull request closed without merging**
