### PR TITLE
Merge pull request #686 from lorifourquet/master

### PR DESCRIPTION
**Pull request by lorifourquet**
Updating to point to latest published USCORE

### CODE REVIEW

**Comment by lmckenzi** [comment]
Git shows no changes?

**Comment by lorifourquet** [comment]
Yet when published to the build site, it shows warning:

The jira specification file appears to be out of date with the versions, artifacts and pages currently defined in the IG. A proposed revised file to be reviewed and, if appropriate, submitted as a pull request against the XML folder in https://github.com/HL7/JIRA-Spec-Artifacts. To see the differences, perform a file compare on 'template/jira-current.xml' (a normalized view of what is in Github) and 'template/jira-new.xml' (reflects current IG content)

**Comment by lmckenzi** [comment]
Ok, but a null commit isn't going to change things.  Have you compared the two files referenced in the message?

**Comment by lmckenzi** [comment]
What's the IG?

**Comment by lorifourquet** [comment]
O cupational data for health (ODH)

Sent from AT&T Yahoo Mail on Android 
 
  On Wed, Jan 18, 2023 at 12:00 PM, Lloyd ***@***.***> wrote:   


What's the IG?

**Comment by lmckenzi** [comment]
Turns out the issue was that you had a local (and broken) copy of your package-list.json file still in your root folder.  I removed it and all now seems happy.

**Pull request closed without merging**
