### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Jeffbrown-MITRE**

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Has the 'specifications' file been updated to reference this new IG?

**Comment by Jeffbrown-MITRE** [comment]
Yes


Jeff

Jeff Brown
Health Standards and Interoperability Lead - FHIR Subject Matter Expert
MITRE Corporation – Health Innovation Center
HL7 certified for  FHIR®, CDA®, and V3 RIM® standards
Co-chair HL7 Financial Management Workgroup
[Diagram  Description automatically generated]<https://www.hl7.org/implement/certificationdirectory.cfm?PersonName=Jeff+Brown>
Co-chair HL7 Implementable Technology Specifications Workgroup

[MITRE: Solving Problems for a Safer World]<https://www.mitre.org/>
• ***@***.******@***.***>
  Å 781-528-3236


From: Lloyd McKenzie ***@***.***>
Sent: Monday, March 21, 2022 12:26 PM
To: HL7/JIRA-Spec-Artifacts ***@***.***>
Cc: Jeff Brown ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [HL7/JIRA-Spec-Artifacts] Add files via upload (PR #472)


@lmckenzi commented on this pull request.

Has the 'specifications' file been updated to reference this new IG?

**Comment by lmckenzi** [comment]
I just checked, and SPECS-FHIR.xml has not been updated to include 'identity-matching'

**Comment by Jeffbrown-MITRE** [comment]
I made the change and made the pull request.

Jeff

Jeff Brown
Health Standards and Interoperability Lead - FHIR Subject Matter Expert
MITRE Corporation – Health Innovation Center
HL7 certified for  FHIR®, CDA®, and V3 RIM® standards
Co-chair HL7 Financial Management Workgroup
[Diagram  Description automatically generated]<https://www.hl7.org/implement/certificationdirectory.cfm?PersonName=Jeff+Brown>
Co-chair HL7 Implementable Technology Specifications Workgroup

[MITRE: Solving Problems for a Safer World]<https://www.mitre.org/>
• ***@***.******@***.***>
  Å 781-528-3236


From: Lloyd McKenzie ***@***.***>
Sent: Monday, March 21, 2022 12:32 PM
To: HL7/JIRA-Spec-Artifacts ***@***.***>
Cc: Jeff Brown ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [HL7/JIRA-Spec-Artifacts] Add files via upload (PR #472)


I just checked, and SPECS-FHIR.xml has not been updated to include 'identity-matching'

**Comment by lmckenzi** [comment]
Not in this pull request.  Should I close this one?

**Comment by Jeffbrown-MITRE** [comment]
Sure

Jeff

Jeff Brown
Health Standards and Interoperability Lead - FHIR Subject Matter Expert
MITRE Corporation – Health Innovation Center
HL7 certified for  FHIR®, CDA®, and V3 RIM® standards
Co-chair HL7 Financial Management Workgroup
[Diagram  Description automatically generated]<https://www.hl7.org/implement/certificationdirectory.cfm?PersonName=Jeff+Brown>
Co-chair HL7 Implementable Technology Specifications Workgroup

[MITRE: Solving Problems for a Safer World]<https://www.mitre.org/>
• ***@***.******@***.***>
  Å 781-528-3236


From: Lloyd McKenzie ***@***.***>
Sent: Monday, March 21, 2022 12:44 PM
To: HL7/JIRA-Spec-Artifacts ***@***.***>
Cc: Jeff Brown ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [HL7/JIRA-Spec-Artifacts] Add files via upload (PR #472)


Not in this pull request. Should I close this one?

**Comment by lmckenzi** [comment]
Dealt with via separate PR

**Pull request closed without merging**
