### PR TITLE
Update for Publish 1.1.0 request

### PR DESCRIPTION
**Pull request by cspears-mitre**

### CODE REVIEW

**Comment by lmckenzi** [comment]
Why is there a '9' in the key for change notes?

**Comment by cspears-mitre** [comment]
> Why is there a '9' in the key for change notes?

It took the file name. The 9 in the file names was to enforce a page order.

**Comment by lmckenzi** [comment]
Sigh.  That was never a great idea.  Ok, I'll approve as is.

**Comment by cspears-mitre** [comment]
> Sigh. That was never a great idea. Ok, I'll approve as is.
Thanks.
I was just keeping it with the convention of this IG thus far. I am not introducing it to other IGs I am working on.

**Pull request merged**
