### PR TITLE
Updating JIRA Spec for fhir.us.ccda aka ccda-on-fhir

### PR DESCRIPTION
**Pull request by jddamore**
Updating based on request from FMG and warning in publisher QA page as part of ballot publication

### CODE REVIEW

**Comment by jddamore** [comment]
<version code="2.0"/> never existed. This was added manually in this github commit 
https://github.com/HL7/JIRA-Spec-Artifacts/commit/d0a280b863d1fa6b086757c8fc6a9f3b684ea128

I have looked in JIRA and no issue for this specification have been logged against 2.0

If you want me to add, I can do so, but it would be confusing since this is version 1.2.0

**Comment by lmckenzi** [comment]
Once a version is committed, it can't be removed.  You can mark it as deprecated.

**Review by lmckenzi — COMMENTED** [review]
Are you actively maintaining all of the other versions?  At minimum I'd expect 1.8.0 to be deprecated.  If you don't expect to ever make technical corrections to 1.0.0, you could mark it as deprecated too.

**Comment by jddamore** [comment]
We are not maintaining any prior versions at this time. I will mark as deprecated

**Comment by lmckenzi** [comment]
I would have expected 1.1.0 to still be active at least?  It's the most recent 'official' release, so you'd still want people to be able to submit feedback against that.

**Comment by brettmarquard** [comment]
Multi version will be confusing to commenters -- I recommend we take all comments on latest

**Comment by jddamore** [comment]
I agree with @brettmarquard (who was an author on the previous 1.1.0 release). Let's just take all feedback on what's balloted. We acknowledge that there's a lot more work to do on other sections and tying everything together with Composition (i.e. the prior work). Let me know if any issue with merging @lmckenzi

**Pull request merged**
