### PR TITLE
Update CDA-ccda-two-one-companion.xml

### PR DESCRIPTION
**Pull request by MLD1995**
Updates for the release of the C-CDA companion guide R4

### CODE REVIEW

**Comment by MLD1995** [comment]
IMPORTANT NOTE: Do not merge until CDA MGMT approval - expected 4/12 or 4/19.

**Comment by lmckenzi** [comment]
Made it a draft so that you can activate it when it's actually ready to merge.

**Comment by MLD1995** [comment]
My bad.  I'd meant to do that but got distracted.  Thanks.

**Comment by lmckenzi** [comment]
Is this now ready to merge?

**Pull request closed without merging**
