### PR TITLE
Preparation for May Ballot

### PR DESCRIPTION
**Pull request by Jeffbrown-MITRE**

### CODE REVIEW

**Comment by MLD1995** [comment]
Looks like this is failing since it's a separate pull request from the one adding the spec file.  The easiest thing would probably be making the change to the SPECS-FHIR.xml file in your local branch that the other pull request is pulling from and then closing this pull request.

**Comment by lmckenzi** [comment]
I need a single pull request that succeeds on its own.  Feel free to close either or both and update/resubmit with all relevant files.

**Comment by Jeffbrown-MITRE** [comment]
Now I am confused as to what worked and what didn’t?

Jeff

Jeff Brown
Health Standards and Interoperability Lead - FHIR Subject Matter Expert
MITRE Corporation – Health Innovation Center
HL7 certified for  FHIR®, CDA®, and V3 RIM® standards
Co-chair HL7 Financial Management Workgroup
[Diagram  Description automatically generated]<https://www.hl7.org/implement/certificationdirectory.cfm?PersonName=Jeff+Brown>
Co-chair HL7 Implementable Technology Specifications Workgroup

[MITRE: Solving Problems for a Safer World]<https://www.mitre.org/>
• ***@***.******@***.***>
  Å 781-528-3236


From: Lloyd McKenzie ***@***.***>
Sent: Monday, March 21, 2022 12:45 PM
To: HL7/JIRA-Spec-Artifacts ***@***.***>
Cc: Jeff Brown ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [HL7/JIRA-Spec-Artifacts] Preparation for May Ballot (PR #473)


I need a single pull request that succeeds on its own. Feel free to close either or both and update/resubmit with all relevant files.

**Comment by MLD1995** [comment]
You've created two different pull requests.  This pull request is pulling from [Jeffbrown-MITRE:master](https://github.com/Jeffbrown-MITRE/JIRA-Spec-Artifacts.) The other pull request is pulling from [Jeffbrown-MITRE:Jeffbrown-MITRE-patch-1](https://github.com/Jeffbrown-MITRE/JIRA-Spec-Artifacts/tree/Jeffbrown-MITRE-patch-1)

This pull request (and thus the master branch that you made) only has the SPECS-FHIR.xml change. The other pull request (and thus the Jeffbrown-MITRE-patch-1 branch that you made) only has the addition of the FHIR-us-identity-matching.xml file.  So you'll need to make one of those changes in the other branch. either adding the FHIR-us-identity-matching.xml file to the master branch or the SPECS-FHIR.xml file to the Jeffbrown-MITRE-patch-1 branch.

**Comment by Jeffbrown-MITRE** [comment]
Ok.  Got it.  Sorry for being confused on this.

Jeff

Jeff Brown
Health Standards and Interoperability Lead - FHIR Subject Matter Expert
MITRE Corporation – Health Innovation Center
HL7 certified for  FHIR®, CDA®, and V3 RIM® standards
Co-chair HL7 Financial Management Workgroup
[Diagram  Description automatically generated]<https://www.hl7.org/implement/certificationdirectory.cfm?PersonName=Jeff+Brown>
Co-chair HL7 Implementable Technology Specifications Workgroup

[MITRE: Solving Problems for a Safer World]<https://www.mitre.org/>
• ***@***.******@***.***>
  Å 781-528-3236


From: MLD1995 ***@***.***>
Sent: Monday, March 21, 2022 12:53 PM
To: HL7/JIRA-Spec-Artifacts ***@***.***>
Cc: Jeff Brown ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [HL7/JIRA-Spec-Artifacts] Preparation for May Ballot (PR #473)


You've created two different pull requests. This pull request is pulling from Jeffbrown-MITRE:master<https://github.com/Jeffbrown-MITRE/JIRA-Spec-Artifacts.> The other pull request is pulling from Jeffbrown-MITRE:Jeffbrown-MITRE-patch-1<https://github.com/Jeffbrown-MITRE/JIRA-Spec-Artifacts/tree/Jeffbrown-MITRE-patch-1>

This pull request (and thus the master branch that you made) only has the SPECS-FHIR.xml change. The other pull request (and thus the Jeffbrown-MITRE-patch-1 branch that you made) only has the addition of the FHIR-us-identity-matching.xml file. So you'll need to make one of those changes in the other branch. either adding the FHIR-us-identity-matching.xml file to the master branch or the SPECS-FHIR.xml file to the Jeffbrown-MITRE-patch-1 branch.

**Pull request closed without merging**
