### PR TITLE
Updated FHIR-us-carin-dic.xml

### PR DESCRIPTION
**Pull request by ekivemark**
default version set to 1.1.0

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Why are you changing http to https for the ci-build?  It's not generally necessary

**Comment by ekivemark** [comment]
> Why are you changing http to https for the ci-build? It's not generally necessary

XML was copied from what was generated by publisher in fHIR-us-carin-dic.xml. I have updated to https urls. Will submit another pull request.

**Comment by ekivemark** [comment]
Changed bi build references to http.

**Comment by lmckenzi** [comment]
As far as I can tell, this PR isn't changing anything anymore?

**Comment by lynnlaakso** [comment]
changes URLS back to http. default version updated to 1.1.0

**Comment by lmckenzi** [comment]
But it shows 0 files as changed.  I'll merge it, but I don't think it's going to do anything.

**Pull request merged**
