### PR TITLE
Update CREDS for ballot

### PR DESCRIPTION
**Pull request by DavidPyke**

### CODE REVIEW

**Comment by lmckenzi** [comment]
Branch isn't letting me auto-update, so may be a conflict?

**Review by lmckenzi — CHANGES_REQUESTED** [review]
Pretty sure your canonical shouldn't be "fhir-registry-protocols-ig" - what's the approved path in your IG proposal?

The ballot link should end with "2023May

**Review by lmckenzi — CHANGES_REQUESTED** [review]
Based on the IG proposal
url="http://hl7.org/fhir/us/fhir-registry-protocols-ig"
should be
url="http://hl7.org/fhir/us/registry-protocols">

Similarly ballot link should be
http://hl7.org/fhir/us/registry-protocols/2023May

**Comment by DavidPyke** [comment]
Okay, I'll change it

**Pull request merged**
