### PR TITLE
Updates for VRDR

### PR DESCRIPTION
**Pull request by AbdulMalikShakir**

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Should some of the versions - particularly 0.1 be marked as deprecated?

**Comment by AbdulMalikShakir** [comment]
> Should some of the versions - particularly 0.1 be marked as deprecated?

All deprecated artifacts and pages have been marked deprecated="true". Should versions be deprecated given the need for version history?

**Comment by lmckenzi** [comment]
Versions that are no longer supported (i.e. that you don't want to accept change requests against and that you won't be making fixes to) should be deprecated.  They'll still remain for historical trackers, but won't be available for new ones.

**Comment by AbdulMalikShakir** [comment]
> Versions that are no longer supported (i.e. that you don't want to accept change requests against and that you won't be making fixes to) should be deprecated. They'll still remain for historical trackers, but won't be available for new ones.

I've deprecated all but the STU1 version and the current CI build version.

**Review by lmckenzi — CHANGES_REQUESTED** [review]
Why do 1.1.0 and 1.0.0 have the same website?  Typically STU updates result in a new website?

**Comment by AbdulMalikShakir** [comment]
> Why do 1.1.0 and 1.0.0 have the same website? Typically STU updates result in a new website?

The STU1.1 has not made it through publication yet. I suspect that when it does the wedsite address will change. Should I change it here now in anticipation?

**Comment by lmckenzi** [comment]
Yes please.

**Comment by AbdulMalikShakir** [comment]
> Yes please.

Done. The URL for version 1.1.0 now points to STU1.1

**Review by lmckenzi — APPROVED** [review]

**Pull request merged**
