### PR TITLE
Update FHIR-us-pdmp.xml for THO code systems

### PR DESCRIPTION
**Pull request by fmckinney**
Also update default version for publishing

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Do you want to mark the 1.0.0-ballot version as deprecated?

**Comment by fmckinney** [comment]
Hi Lloyd,

This might be a stupid question, but is it the best practice to deprecate the ballot version before publishing?

Thanks!
Frank


FrankMcKinneyGroup LLC | 952-201-4520 | ***@***.******@***.***> | www.frankmckinney.com<http://www.frankmckinney.com/>

This e-mail and any attachments are confidential, may contain sensitive information, and are intended solely for the individual to whom this e-mail is addressed. If you have received this e-mail in error, please notify the sender by reply e-mail immediately and destroy all copies of the e-mail and any attachments.

**Comment by lmckenzi** [comment]
It's best practice to deprecate any versions you no longer want to accept comments about when you're creating a new version.  Ballot releases will typically fall into that category, but not always.

**Comment by fmckinney** [comment]
Ah. That makes sense

I’ll cancel this pull request and make another that includes deprecating the ballot version

Thanks Lloyd,
Frank


FrankMcKinneyGroup LLC | 952-201-4520 | ***@***.******@***.***> | www.frankmckinney.com<http://www.frankmckinney.com/>

This e-mail and any attachments are confidential, may contain sensitive information, and are intended solely for the individual to whom this e-mail is addressed. If you have received this e-mail in error, please notify the sender by reply e-mail immediately and destroy all copies of the e-mail and any attachments.

**Pull request closed without merging**
