### PR TITLE
vrcl + deprecating versions that I don't want to get jira tickets about

### PR DESCRIPTION
**Pull request by saulakravitz**

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Should earlier versions be deprecated?

**Comment by saulakravitz** [comment]
STU1 versions still referenced by active publications.   
Next round of publication we can deprecate 'em.

**Review by lmckenzi — COMMENTED** [review]
Do you want 1.0.0 and 1.1.0 to still be active?

**Comment by saulakravitz** [comment]
Uncle.  I marked a bunch of versions that I don't want to get jira tickets about as deprecated.

**Pull request merged**
