### PR TITLE
Updating Pathology Jira spec files with correct cannonical URLs

### PR DESCRIPTION
**Pull request by dadmbc**

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
"www." shouldn't appear in the HL7 URLs
You're missing a 'current' version
You'll need to specify the URL for the 0.1.0 version, which should be the ballot URL - i.e. end in "/2021-Sep"

**Comment by dadmbc** [comment]
Updated all HL7 URLs to remove www. 
"current" version is the first entry in package-list.json list (starting on line 3 here https://github.com/HL7/cancer-reporting/blob/master/package-list.json)
Updated URL for v0.1.0 to "2021-SEP"

**Comment by dadmbc** [comment]
Please let me know if any further changes to package-list.json or examples are needed. Thanks

**Comment by lmckenzi** [comment]
Still missing the 'current' version and the url for 0.1.0

**Comment by dadmbc** [comment]
Have updated both jackage-list.json and JiraSpecArtifacts files

**Review by lmckenzi — CHANGES_REQUESTED** [review]
cancer-reporting looks great.  Please make the equivalent changes to common-libraries.

**Comment by dadmbc** [comment]
Thanks again for the help. Common libraries is being withdrawn from ballot

**Comment by lmckenzi** [comment]
Ok.  It should still have a URL for the 'current' release.

**Comment by dadmbc** [comment]
Agreed- both UV's package-lsit.json and JiraSpec have been updated

**Review by lmckenzi — APPROVED** [review]

**Pull request merged**
