### PR TITLE
Upate to CardX-HTN-MNG IG

### PR DESCRIPTION
**Pull request by nrdavis1**
Need to update the Jira Spec file for the CardX-HTN-MNG implementation guide.  This is to support the ballot version.  not worried about the CIMI Labs IG for now.

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
/index.html should not be in the CI-build URL
Initial version should be 1.0.0-ballot, not 0.0.1
CIMI labs 1.0.0 should not have a 2023Sep URL.  Is this a ballot release or an official publication?

**Comment by nrdavis1** [comment]
Updated the Jira Spec file and the IG files.  All pushed.

**Comment by nrdavis1** [comment]
Please ignore the CIMI Labs commits for now if you can.

**Comment by lmckenzi** [comment]
I can't ignore anything in the pull request.  Please close this request and submit a separate pull request with only what you want committed

**Pull request closed without merging**
