### PR TITLE
update vrdr

### PR DESCRIPTION
**Pull request by saulakravitz**

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
To clarify, your 'official release' is going to be 1.9.0 and not 2.0.0 (and jumping from 1.1.0)?

**Comment by saulakravitz** [comment]
Official release will be 2.0.0.....
I was going to bump it to 2.0.0 when we submit the publication checklist.  Should I do it now?

**Comment by saulakravitz** [comment]
Bumped it to 2.0.0 in prep for STU2 publication in the very near future.

**Comment by lmckenzi** [comment]
If you're going to ballot with the intention of publishing as 2.0.0, it should be 2.0.0-ballot.  If you're prepping for the actual imminent 2.0.0 release, it should be 2.0.0

**Comment by saulakravitz** [comment]
It is updated to 2.0.0 with the intention to publish as such....please merge

**Pull request merged**
