### PR TITLE
Updated FHIR-us-pacio-adi.xml for STU1 publication

### PR DESCRIPTION
**Pull request by mlterryMitre1**

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
The URL for 1.0.0 should be "http://hl7.org/fhir/us/pacio-adi/STU1"

**Review by lmckenzi — CHANGES_REQUESTED** [review]
<version code="1.0.0" url="http://hl7.org/fhir/us/fhir-pacio-adi"/>
should be
<version code="1.0.0" url="http://hl7.org/fhir/us/pacio-adi/STU1"/>

**Comment by mlterryMitre1** [comment]
@lmckenzi - re the error: "_[schemavalidate] /home/runner/work/JIRA-Spec-Artifacts/JIRA-Spec-Artifacts/xml/FHIR-us-pacio-adi.xml:33:182: cvc-identity-constraint.4.1: Duplicate unique value [Care Plan for Unconscious, vegetative state, coma] declared for identity constraint "artifact-name-unique" of element "specification"_.

Since this value is used in two completely different examples, shouldn't this be allowable?
That phrase is used in the examples, one for McBee, the other for Betsy Smith-Johnson.  It is completely reasonable that the same value is used in both locations as they are separate resources for separate patients.

Please advise.

**Comment by lmckenzi** [comment]
Every artifact in the IG must have a unique title.  (When you look at the table of contents, there shouldn't be any duplicate names, because that's confusing to the reader.)

**Comment by mlterryMitre1** [comment]
@lmckenzi - we're going with Dave Hill's PR #859 for the PACIO ADI IG since it passed. I'll remove my PullRequest.

**Pull request closed without merging**
