### PR TITLE
Add uv eyecare

### PR DESCRIPTION
**Pull request by oridashi**
submission for new IG addition

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
If you're going to ballot, your version should be 0.1.0, not 1.0.0.  (The latter will be the version for your final publication request when you're ready to publish the STU release.)

**Comment by lmckenzi** [comment]
Also looks like your file isn't valid XML

**Comment by oridashi** [comment]
> Also looks like your file isn't valid XML
Thanks Lloyd

**Comment by lmckenzi** [comment]
The QA check build failed with quite a few issues - check the 'details' to see all of the messages.

**Comment by oridashi** [comment]
was not sure what the cause of this error is?

**Comment by lmckenzi** [comment]
The file you're committing is "FHIR-uv-eycare.xml" and the specification file expects it to be "FHIR-uv-ey**e**care.xml "

**Pull request merged**
