### PR TITLE
first stab at updating fhircast' file

### PR DESCRIPTION
**Pull request by isaacvetter**
as part of moving FHIRcast to an IG.

### CODE REVIEW

**Comment by isaacvetter** [comment]
@lmckenzi -- Mr McKenzie, this PR is now passing the automated checks! Would you be so kind as to merge it as your earliest convenienece?

**Comment by lmckenzi** [comment]
I *can*.  However, I see that a bunch of your keys reflect section hierarchy.  Be aware that once the key exists, it's immutable.  Even if the section moves, if it's the same content, the key needs to stay the same.  Do you really *want* to put section numbers in the keys?

**Comment by isaacvetter** [comment]
Lloyd,

Thank you, you're exactly right. Your suggestion is implemented, I also cleaned up the page key names in general. Any other feedback along these lines?

Isaac

**Comment by lmckenzi** [comment]
Only other feedback is that the 'dropdown' in Jira will be in the order you list things in.  Most of the time you want it to be alphabetical because that makes it easier for people to scroll and find.  Though sometimes, you might want to put super-common things up at the top.  I'll wait for your confirmation before merging.

**Comment by isaacvetter** [comment]
@lmckenzi - thank you, alphabetized keys, with some meangingful exceptions. As soon as you have time, please do merge.

**Pull request merged**
