### PR TITLE
Updates for new versions of HAI and HAILTC

### PR DESCRIPTION
**Pull request by minigrrl**

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
Should any of the versions be deprecated?  Typically when you put out a technical correction you'd deprecate the prior versions because you can't accept changes against the originals anymore.  All changes need to be with respect to the new TC

**Comment by minigrrl** [comment]
@lmckenzi Right now we don't want to deprecate any of the older versions. The latest one won't be started to be implemented for another year. We want to keep them all open for comments.

**Comment by minigrrl** [comment]
Ok, I will update.

Sarah Gaunt (she, her)
Senior Information Analyst
t: +61 410 292 506
Brisbane, Australia (Australian Eastern Standard Time)
***@***.******@***.******@***.***<http://www.lantanagroup.com/>

**Comment by minigrrl** [comment]
@lmckenzi I have deprecated the versions that can't be updated

**Pull request merged**
