### PR TITLE
Update FHIR-pddi.xml

### PR DESCRIPTION
**Pull request by rkboyce**
This is to update the JIRA specification for the PDDI implementation guide project.

### CODE REVIEW

**Comment by lmckenzi** [comment]
Why are no artifacts listed?

**Comment by brynrhodes** [comment]
Would the profiles be the artifacts?

Also, the default workgroup should be cds I think, not pharma?

**Comment by lmckenzi** [comment]
Yes, and maybe value sets, etc.  The publisher generates  suggested file

**Comment by brynrhodes** [comment]
@lmckenzi , I've looked through the output of the publisher and can't find the suggested file, can you point me to where this would be?

**Comment by lmckenzi** [comment]
It should show up in your root folder - FHIR-uv-pddi.xml

**Comment by brynrhodes** [comment]
I've run the build with the latest publisher and can't find a file anywhere with that name (or anything close to it). Is there some switch I have to set to get the publisher to generate that?

**Comment by lmckenzi** [comment]
You have to be using the HL7 template, which it looks like PDDI is not...

**Comment by maxsibilla** [comment]
FHIR-pddi.xml has been updated with artifacts

**Pull request merged**
