### PR TITLE
update jira file for snapshot

### PR DESCRIPTION
**Pull request by Healthedata1**

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Has grahame confirmed that's the name?

**Comment by Healthedata1** [comment]
not yet

**Comment by Healthedata1** [comment]
yes https://chat.fhir.org/#narrow/stream/179192-fmg/topic/Expectations.20for.20non-ballot-review.20snapshots/near/360944282

**Comment by Healthedata1** [comment]
grumble grumble... ok

**Pull request closed without merging**
