### PR TITLE
Update FHIR-us-udap-security.xml for STU2 ballot

### PR DESCRIPTION
**Pull request by lcmaas**

### CODE REVIEW

**Comment by lcmaas** [comment]
@lmckenzi, I used the URL path ending that Marc Duteau sent me via email following the QA review. He did not mention any other issues with the publication request. The status is currently set to "ballot". Could you please clarify if this is not what you are asking about? Thanks.

**Comment by lmckenzi** [comment]
I'm referring to the publication-request.json file.  Is it identifying your release as having a status of 'ballot'?

**Comment by lcmaas** [comment]
@lmckenzi  yes, the publication-request.json file identifies this release as having a status of 'ballot'

**Comment by lmckenzi** [comment]
When I build your IG the proposed JiraSpec file has the correct ballotUrl.  Your pull request does not.

**Comment by lcmaas** [comment]
@lmckenzi I've updated the ballotUrl attribute

**Pull request merged**
