### PR TITLE
New for MDI

### PR DESCRIPTION
**Pull request by DianaWright61**

### CODE REVIEW

**Comment by DianaWright61** [comment]
This is for the MDI IG. Is there anything else I can do to get this schema valid?

**Comment by lmckenzi** [comment]
Current validation issues:  The content of element 'specification' is not complete. One of '{version, artifactPageExtension, artifact, page}' is expected.

Have you tried running the XML through a schema validator?

**Comment by DianaWright61** [comment]
It has     <version code="1.0.0-ballot"/>. 
Should I try adding one artifact?

**Comment by lmckenzi** [comment]
The schema mandates that you have at least one version and one page

**Pull request merged**
