### PR TITLE
CRMI IG 1.0.0-ballot2 update

### PR DESCRIPTION
**Pull request by brynrhodes**

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
There are a *lot* of deprecated artifacts here.  Are any of them due to renames, or are they all genuinely gone?

**Comment by brynrhodes** [comment]
Combination of things:

1. There were extension pack extensions that hadn't been published in an extension pack yet last time around, so now that they are in the extension pack I could remove them from the IG
2. Several of the profiles moved to the CQL IG, so those are genuine removals
3. I renamed a bunch of the example artifacts to clarify what examples they were for

**Comment by lmckenzi** [comment]
Renamed ones should keep the old keys rather than deprecating and creating new ones

**Comment by brynrhodes** [comment]
Okay, but then how does the generation know what the key is?

**Comment by lmckenzi** [comment]
If you've changed a name and it's deprecating the old one and adding the new one, grab the old key (deprecated row) and stick it with the new name (new row) and delete the deprecated row.  This has to be done manually.

**Comment by brynrhodes** [comment]
Okay, fixed the ones I could, several of the ones that were changed it complained that they were being removed.

**Pull request merged**
