### PR TITLE
Update FHIR-us-davinci-atr.xml

### PR DESCRIPTION
**Pull request by nbashyam**
Update to match build for ballot.

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
I think the ballot URL is just going to be 2020Feb, not 2.0.0-ballot...

**Comment by nbashyam** [comment]
> I think the ballot URL is just going to be 2020Feb, not 2.0.0-ballot...

You mean 2023Feb right not 2020Feb ?

**Comment by lmckenzi** [comment]
Yes

**Comment by nbashyam** [comment]
Obsolete.

**Pull request closed without merging**
