### PR TITLE
Version 3.0.0.  path 2023May

### PR DESCRIPTION
**Pull request by saulakravitz**

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
The URLs look wrong.  Should be:
version code="3.0.0" url="http://hl7.org/fhir/us/mcode/STU3"
version code="3.0.0-ballot" deprecated="true" url="http://hl7.org/fhir/us/mcode/2023May"

Also, if you're just going to ballot, 3.0.0 shouldn't be there at all yet.

**Comment by saulakravitz** [comment]
I changed defaultURL to current
Changed 3.0.0 to 2023May....

Is that what needs done?

**Comment by lmckenzi** [comment]
I fixed my comment so it renders properly

**Comment by saulakravitz** [comment]
3.0.0 is gone
3.0.0-ballot is deprecated....

Are we there yet?

**Comment by lmckenzi** [comment]
version code="3.0.0-ballot" url="http://hl7.org/fhir/us/mcode/2023May"

That's what you should have for the ballot.  The new code shouldn't be there at all.

**Comment by saulakravitz** [comment]
Hopefully now we are there.

**Pull request merged**
