### PR TITLE
Changes to FHIR-us-covid19.xml file

### PR DESCRIPTION
**Pull request by nrdavis1**
Made modifications according to Lloyd McKenzie's comments and applied fix to pass build.

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
Still missing the version url and the 'current' version.

**Comment by nrdavis1** [comment]
@lmckenzi Can you give mean example of what the version URL looks like as well as the current version?  I'm comparing what I have to other files and don't see any difference.

**Comment by lmckenzi** [comment]
Your versions should look something like this:
<version code="current" url="http://build.fhir.org/ig/HL7/cdisc-map"/>
<version code="0.1.0" url="http://hl7.org/fhir/uv/cdisc-mapping/2021Jan"/>

**Comment by nrdavis1** [comment]
@lmckenzi I don't see the examples you provided.  Did you attach them?

**Comment by lmckenzi** [comment]
Sorry.  Looks like Git doesn't like pasted XML.  Updated my post above to escape the open-brackets.

**Pull request closed without merging**
