### PR TITLE
Update CCDA-on-FHIR for Jan 2025 Ballot

### PR DESCRIPTION
**Pull request by benjaminflessner**

### CODE REVIEW

**Comment by MLD1995** [comment]
Looks like it has a duplicate value.  <page key="FC-medications" name="FHIR to C-CDA Medications"/> appears twice.  Not sure what's up with that.

**Comment by jlyle1** [comment]
removed duplicate page

**Comment by lmckenzi** [comment]
Needs to be updated to the current base branch

**Comment by lmckenzi** [comment]
And again :(  Normally it lets me do it from within Github, but it's not showing that option for some reason.

**Pull request merged**
