### PR TITLE
fhir-mdi

### PR DESCRIPTION
**Pull request by saulakravitz**

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
Version should be 2.0.0-ballot
name of "MessageDefinitionToxicologySystem" looks like a computable name, not a title.

**Comment by saulakravitz** [comment]
Tweaked per your comments...thx

**Review by lmckenzi — COMMENTED** [review]
You changed the default version to be the ballot for two of them, but not the third.  Typically we leave the default to be the official release, not the ballot version.  Are the defaults all set as you truly intend?

**Comment by saulakravitz** [comment]
In the absence of direction how to configure this for the ballot I grope around each time.
It would be great if there was a short ballot cheat sheet on what is desired/expected.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Lloyd McKenzie ***@***.***>
Sent: Wednesday, March 20, 2024 7:06:42 PM
To: HL7/JIRA-Spec-Artifacts ***@***.***>
Cc: Saul A Kravitz ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [HL7/JIRA-Spec-Artifacts] fhir-mdi (PR #959)

@lmckenzi commented on this pull request. You changed the default version to be the ballot for two of them, but not the third. Typically we leave the default to be the official release, not the ballot version. Are the defaults all set as you


@lmckenzi commented on this pull request.

You changed the default version to be the ballot for two of them, but not the third. Typically we leave the default to be the official release, not the ballot version. Are the defaults all set as you truly intend?

**Comment by saulakravitz** [comment]
All of the JiraSpec changes except for mCODE STU4 should be here:


| File | Parameter | VRDR STU3 | MDI STU2 | CodexRT STU2 | 
| -- | -- | -- | -- | -- | 
|Jira-Spec | (Latest Version) | 3.0.0-ballot | 2.0.0-ballot | 2.0.0-ballot | 
|Jira-Spec | defaultVersion | 2.2.0 | 1.1.0 | 1.0.0 | 
|Jira-Spec | Versions deprecated | No changes | No changes | No changes |

**Pull request merged**
