### PR TITLE
Update PDDI

### PR DESCRIPTION
**Pull request by brynrhodes**

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Why are you jumping from 0.2.0 to 2.0.0-ballot?  Shouldn't it be 1.0.0-ballot?

**Comment by brynrhodes** [comment]
Because this is STU2, so trying to keep the version aligned with the STU

**Comment by lmckenzi** [comment]
In your versions, I don't see that there's ever been a 1.0.0 release?  (Or any non-ballot release)

**Comment by brynrhodes** [comment]
Okay, I checked the ballot pool and it is listed as STU1, so I updated the version to 1.0.0-ballot. Once this PR is merged I'll commit the updates to the PDDI repository to change the version and ballot title to match.

**Pull request merged**
