### PR TITLE
Standard Personal Health Record (SPHR) - First Attempt

### PR DESCRIPTION
**Pull request by awatson1978**
- First attempt at defining JIRA Spec Artifacts to enable SPHR for balloting.
- Was not able to find the `.buildLocal.bat` file.  
- Did my best to follow all other instructions.

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
Why is the version 0.4.6?  Typically the first version should be 1.0.0-ballot.  (I.e. first ballot leading to a planned 1.0.0 release)

Your publication request should indicate the expected URL for the 1.0.0-ballot release as [canonical]/2025Jan (assuming that you're targeting a January ballot)

**Comment by awatson1978** [comment]
Mmmm...  because we've had 4 internal restructurings of the content so far, and 6 minor revisions to page content within the most recent restructuring.  I'll update the version and url accordingly....

**Comment by lmckenzi** [comment]
From a labeling perspective, you've got CI-build until such time as you're ready to go to ballot, at which point the label is driven by the version of what the target post-ballot publication will be

**Comment by awatson1978** [comment]
Mmmm....   what exactly _is_ the canonical URL?  I know where the build URL is....
https://build.fhir.org/ig/HL7/personal-health-record-format-ig/

I see the "Official URL" is:
https://open-health-manager.github.io/standard-patient-health-record-ig/ImplementationGuide/StandardPatientHealthRecordIG

Is that it?

**Comment by lmckenzi** [comment]
The canonical URL will be:
http://hl7.org/fhir/[realm]/[code]
where the realm and code are whatever was approved in your IG proposal.

As an example, the canonical for US core is: `https://hl7.org/fhir/us/core`

The most recent ballot URL was `https://hl7.org/fhir/us/core/2024Jan`

**Comment by awatson1978** [comment]
Okay... I'm thinking the URLs may be sorted out now.

**Comment by awatson1978** [comment]
@lmckenzi

**Comment by lmckenzi** [comment]
Did you see the results of the build?  
```
[schemavalidate] /home/runner/work/JIRA-Spec-Artifacts/JIRA-Spec-Artifacts/xml/FHIR-sphr.xml:2:356: cvc-enumeration-valid: Value 'patientempowerment' is not facet-valid with respect to enumeration '[gas, arb, as, att, brr, cbcc, cdamg, cgit, cimi, cds, cic, cg, cgp, cqi, dev, ec, ehr, director, fgb, fhir-i, fmg, fm, hcd, hsi, hss, hta, ic, project, ii, its, inm, lhs, mh, mnm, oo, pa, pc, pe, pie, pharm, pic, ps, pher, pubs, security, soa, sd, sgb, templates, tsc, tsmg, us-realm, vocab, v2mg, eu, au-v2, au-fhir]'. It must be a value from the enumeration.
[schemavalidate] /home/runner/work/JIRA-Spec-Artifacts/JIRA-Spec-Artifacts/xml/FHIR-sphr.xml:2:356: cvc-attribute.3: The value 'patientempowerment' of attribute 'defaultWorkgroup' on element 'specification' is not valid with respect to its type, 'WorkGroup'.
[schemavalidate] /home/runner/work/JIRA-Spec-Artifacts/JIRA-Spec-Artifacts/xml/FHIR-sphr.xml:38:104: cvc-identity-constraint.4.1: Duplicate unique value [StructureDefinition/pcd-sleep-observation] declared for identity constraint "artifact-id-unique" of element "specification".
```
The work group code is "pe".  You'll need to fix the duplicate id value too.

**Pull request merged**
