### PR TITLE
Updating ballot Url from /2021-SEP to /2021Sep

### PR DESCRIPTION
**Pull request by dadmbc**
Updating ballot URL from 2021-SEP to /2021Sep

### CODE REVIEW

**Comment by dadmbc** [comment]
Automated checks usually don't take this long, is there something I can do to nudge it?

**Comment by lmckenzi** [comment]
I nudged, but that doesn't seem to have helped.  Have reached out for support

**Comment by lmckenzi** [comment]
There was something wonky with Git.  Can you make a whitespace change and push the update to force it to retry?

**Comment by dadmbc** [comment]
Seems to have worked, ty

**Pull request merged**
